FROM geopython/stetl:local

WORKDIR /stetl

ENV BUILD_DEPS="python3-pip python3-setuptools python3-dev python3-wheel"

# Install required classes for testing
RUN \
	apt-get update && apt-get --no-install-recommends install -y ${BUILD_DEPS} \
	&& pip3 install -r requirements-dev.txt \
	&& apt-get remove --purge ${BUILD_DEPS} -y && apt autoremove -y && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["nose2"]
